package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	SSMDocumentName            *encoding.String   `json:"TPSCode,omitempty"`
	SSMDocumentVersion         *encoding.String   `json:"Title,omitempty"`
}

/*
// Memo is autogenerated from the json schema
type Memo struct {
	Heading *encoding.String
	Body    *encoding.String
}
*/
